In [4]:
# For Colab to use Tensorflow 2.X
from __future__ import absolute_import, division, print_function, unicode_literals

try:
  %tensorflow_version 2.x
except Exception:
  pass


In [5]:
import tensorflow as tf
import numpy as np

In [6]:
class One_Feature_Node:
  def __init__(self):
    self.w = tf.Variable([[0.1]])
    self.b = tf.Variable([[0.1]])

  def __call__(self, x):
    return self.get_output(x)

  def get_output(self, x):
    out = tf.matmul(x, self.w)
    out = tf.add(out, self.b)
    out = tf.math.sigmoid(out)
    return out

In [9]:
x = tf.constant([[1.0]])

one_feature_node = One_Feature_Node()
one_feature_node(x)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.54983395]], dtype=float32)>

In [6]:
class Two_Feature_Node:
  def __init__(self):
    self.w = tf.Variable([[0.1], [0.2]])
    self.b = tf.Variable([[0.1]])
    
  def __call__(self, x):
    return self.get_output(x)
  
  def get_output(self, x):
    out = tf.matmul(x, self.w) #can be done in O(1) even with the multiple data
    out = tf.add(out, self.b)
    out = tf.math.sigmoid(out)
    return out

In [18]:
#two features for one data
x = tf.constant([[1.0, 2.0]])

two_feature_node = Two_Feature_Node()
two_feature_node(x)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.6456563]], dtype=float32)>

In [9]:
#multiple input data with two features
x = tf.constant([[1.0, 2.0], [2.0, 3.0], [4.0, 5.0]])
two_feature_node = Two_Feature_Node()
two_feature_node(x)

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[0.6456563 ],
       [0.7109495 ],
       [0.81757444]], dtype=float32)>

In [7]:
tf.random.set_seed(1)
np.random.seed(1)

In [7]:
class Node:
  def __init__(self):
    self.w = tf.Variable(tf.random.normal([2, 1]))
    self.b = tf.Variable(tf.random.normal([1, 1]))

  def __call__(self, x):
    return self.preds(x)
  
  def preds(self, x):
    out = tf.matmul(x, self.w)
    out = tf.add(out, self.b)
    out = tf.nn.sigmoid(out)
    return out

  def loss(self, y, y_pred): #loss function
    return tf.reduce_mean(tf.square(y_pred - y))

  def train(self, inputs, outputs, learning_rate):
    epochs = range(10000)
    for i, epoch in enumerate(epochs):
      with tf.GradientTape() as t:
        current_loss = self.loss(self.preds(inputs), outputs) #calculate loss
        if i % 1000 == 0:
          print(str(i) + "th epoch, loss : " + str(current_loss.numpy()))

        #backpropagation
        dw, db = t.gradient(current_loss, [self.w, self.b]) #calculate gradient
        self.w.assign_sub((learning_rate * dw))
        self.b.assign_sub((learning_rate * db))

In [8]:
#AND operation
inputs = tf.constant([[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0]])
outputs = tf.constant([[0.0], [0.0], [0.0], [1.0]])

node = Node()
node.train(inputs, outputs, 0.01)

#test
assert node([[0.0,0.0]]).numpy()[0][0] < 0.5
assert node([[0.0,1.0]]).numpy()[0][0] < 0.5
assert node([[1.0,0.0]]).numpy()[0][0] < 0.5
assert node([[1.0,1.0]]).numpy()[0][0] >= 0.5

0th epoch, loss : 0.17513402
1000th epoch, loss : 0.08886799
2000th epoch, loss : 0.071351275
3000th epoch, loss : 0.06387137
4000th epoch, loss : 0.05824548
5000th epoch, loss : 0.053707756
6000th epoch, loss : 0.049904104
7000th epoch, loss : 0.04662943
8000th epoch, loss : 0.043757536
9000th epoch, loss : 0.041206293
